### ISSUE TITLE
Toolbar: when using the toggle version of the toolbar filters the toolbar unnecessarily takes too much vertical space

### ISSUE THREAD

**Issue by KKoukiou** [patternfly/patternfly-design#1055]
Current patternfly:

![Screen Shot 2021-06-02 at 09 46 55](https://user-images.githubusercontent.com/14921356/120286453-8b34cc00-c2be-11eb-803e-95171c83d6ef.png)

Expected result:

![Screen Shot 2021-06-02 at 09 46 38](https://user-images.githubusercontent.com/14921356/120286456-8bcd6280-c2be-11eb-90ae-9ea61f08c9db.png)

Since we are dealing here with mobile mode, a few pixels are important to be saved. Our designer added some custom CSS to achieve this result. The CSS follows:
``` css

// Wrap the filter info
.services-toolbar.pf-c-toolbar {
    display: flex;
    flex-wrap: wrap;

    > .pf-c-toolbar__content:first-child {
        flex: auto;
    }

    .pf-c-toolbar__content-section {
        width: auto;
    }
}
```
