### ISSUE TITLE
[ProgressStepper] - indicate progress between (long-running) steps

### ISSUE THREAD

**Issue by garrett** [patternfly/patternfly-design#1181]
**Is this a new component or an extension of an existing one?**
Progress Stepper component

**Describe the feature**
Display in-between progress for steps that take a while.

For the new Anaconda (OS installation for Fedora, RHEL, CentOS, Alma, Rocky, etc.) implementation using PatternFly, during a usability test, there wasn't enough granular feedback for the process. The stepper component was used, but each step could take some time between several seconds to several minutes.

**Are there visuals for this feature? If applicable, please include examples for each state and for varying widths**

Here's a quick idea that would blend the progress bar experience into the progress stepper, so the stepper works as it does currently, but in-between progress shows up as a progress-bar-like line.
![PatternFly 4 • Progress stepper](https://user-images.githubusercontent.com/10246/178994267-7289450d-a58e-4e9d-b34b-be82bcaf91f2.png)

Source SVG: [Progress stepper.svg](https://user-images.githubusercontent.com/10246/178994279-fe6082c9-d108-4bd5-a2f2-e5bf618cd0e2.svg)

An additional idea is that we could even have a spinner on the current step. But that's probably overkill. :wink:

**Comment by garrett** [comment]
I've implemented the mockup in basically 5 lines of CSS (mainly to set colors and a width for percentage), where the percentage is exposed as a number (representing a percentage), which React can modify.

Demo:
https://codesandbox.io/s/unruffled-benji-cx657r?file=/progress-demo.scss

Screenshot:

![stepper progress](https://user-images.githubusercontent.com/10246/181002618-7867dd8a-9566-4856-9641-2da09e0fb264.png)


---

Most of the content below are pulled directly from [PatternFly's basic demo for the stepper](https://www.patternfly.org/v4/components/progress-stepper#basic), in JSX. We'd probably want to set the progress colors to the same color, like a progress color variable (unless we want past, active, and future to be the same). In the mockup, I merged the colors of past and current and leave future the default color.

When progress isn't set, the width between steps is 0%, so it works by default to indicate past and current step, but not current progress.

Current progress is relative to the step, not the overall progress.

SCSS:

```scss
// Example CSS
.pf-m-success {
  // Demo colors
  --pf-c-progress-stepper__step-icon--BorderColor: green;
  --pf-c-progress-stepper__step-connector--before--BorderBottomColor: green;
}

.pf-m-current {
  // Another demo color (could be the same as the success colors)
  --pf-c-progress-stepper__step-icon--BorderColor: red;
}

.pf-c-progress-stepper__step:not(:last-of-type) > .pf-c-progress-stepper__step-connector::after {
  // Unique to ::after
  --pf-c-progress-stepper__step-connector--before--BorderBottomColor: red;
  width: calc(var(--pf-c-progress-stepper__step-percent) * 1%);

  // /////////////////////////////////////////////////////////////
  // Shared in common with ::before (from PF)
  position: absolute;
  top: var(--pf-c-progress-stepper__step-connector--before--Top);
  left: var(--pf-c-progress-stepper__step-connector--before--Left);
  height: var(--pf-c-progress-stepper__step-connector--before--Height);
  content: "";
  border-right: var(--pf-c-progress-stepper__step-connector--before--BorderRightWidth) solid var(--pf-c-progress-stepper__step-connector--before--BorderRightColor);
  border-bottom: var(--pf-c-progress-stepper__step-connector--before--BorderBottomWidth) solid var(--pf-c-progress-stepper__step-connector--before--BorderBottomColor);
  transform: var(--pf-c-progress-stepper__step-connector--before--Transform);
}
```

JSX:

```jsx
import ReactDOM from "react-dom";
import "@patternfly/react-core/dist/styles/base.css";
import "./fonts.css";
import "./progress-demo.scss";

import React from "react";
import { ProgressStepper, ProgressStep } from "@patternfly/react-core";

const Basic = () => (
  <ProgressStepper>
    <ProgressStep
      variant="success"
      id="basic-step1"
      titleId="basic-step1-title"
      aria-label="completed step, step with success"
    >
      First step
    </ProgressStep>
    <ProgressStep
      variant="info"
      isCurrent
      id="basic-step2"
      titleId="basic-step2-title"
      aria-label="step with info"
      // Implemented here as a style, so I didn't have to change any PF JS;
      // ideally, it would be exposed as a property
      style={{ "--pf-c-progress-stepper__step-percent": 50 }}
    >
      Second step
    </ProgressStep>
    <ProgressStep
      variant="pending"
      id="basic-step3"
      titleId="basic-step3-title"
      aria-label="pending step"
    >
      Third step
    </ProgressStep>
  </ProgressStepper>
);

const rootElement = document.getElementById("root");
ReactDOM.render(<Basic />, rootElement);
```
